### ISSUE TITLE
Map Guide Button

### ISSUE THREAD

**Issue by Danhanado** [Hipnosis183/TTX-Monitor#3]
Hi there, currently I can map every button on my xinput fightstick except for the guide button which i'd like to use to exit the game, would it be possible to fix that?

**Comment by Hipnosis183** [comment]
That's a limitation of DirectInput, which is what I'm using to handle controllers. And after doing some research, it looks like even XInput doesn't expose the guide button for program usage, or at least is not documented.

I also tried with JConfig and it doesn't support it either.

I won't look into it, so your best bet could be mapping to keyboard and setup something like Joy2Key, which apparently does the trickery necessary to allow the guide button to be mapped. Not ideal but the best solution, good luck.
